export const SuccessStoriesData = [
  {
    storyTitle:
      "First Wave of COVID-19 (plasma bank and awareness program with former president - pictures)",
    storyDetail:
      "The first COVID-19 case in Nepal was confirmed on January 23, 2020. While China and several other European countries were severely hit till the time the first case was confirmed, the government was dilly-dallying, making insensitive comments about the pandemic and risking our lives. Though the government implemented a lockdown in a bid to curb the spread of coronavirus, there were no other safety measures or preparations from the side of the government. There was a lack of PCR-tests for individuals by the government and one had to pay a hefty price for coronavirus PCR test. HamiNepal supported a movement, demanding better handling of the coronavirus situation in Nepal. The movement was a huge success and the government made PCR tests available at an affordable price. While the virus was new for the nation, every individual was looking out for themselves. Anyone infected with COVID-19 was looked upon as an ‘untouchable’ person even after the recovery.However, at a time when COVID-19 recovered people were suffering from stigma, the World Health Organisation (WHO) made an incredible announcement. The WHO announced that plasma of COVID-19 recovered people was shown effective for treatment of coronavirus patients. HamiNepal, in collaboration with former president of Nepal Dr. Ram Baran Yadav and several celebrities, organised an awareness campaign in a bid to change the perspective of people towards COVID-19 affected patients. Not only that, HamiNepal team co-ordinated with Tribhuvan University Teaching Hospital and the Ministry of Health to collect plasma from those recovered from COVID-19. The plasma received from single COVID-19 recovered patients was used for treatment of three coronavirus patients.",
  },
  {
    storyTitle: "Second Wave of COVID-19",
    storyDetail: "Currently the second wave of COVID-19 surge has put an enormous burden on an already strained and dilapidated health infrastructure. HamiNepal is trying its best to address the need of hospital beds, critical oxygen among other medical equipment and supplies.With the surge in cases leading to lack of hospital beds, HamiNepal had helped Bir Hospital to make its new building functionable. The volunteers had set-up 170 beds in the new building of Bir Hospital within a 3 days time period. The team also donated extra 50 beds to the hospital.Similarly, HamiNepal provided portable X-ray machines and 5 ICU beds to the National Trauma Center. The organisation has also helped Chhetrapati Free Clinic to run as a ‘COVID designated hospital’ by providing sanitisers, high-flow nasal canulas, 5 ICU beds, 10 hospital beds, 25 mattresses and 30 side-tables.Besides this, HamiNepal is the first organisation to bring 520 oxygen cylinders via chartered flight along with other medical supplies from the received donation amount.As many as 270 oxygen cylinders, 50 beds, 50,000 masks and 100 PPE equipment were sent to Sudurpaschim local volunteers to be distributed to hospitals battling the coronavirus pandemic.",
  },
];